#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
# zmodload zsh/zprof

# init MacTeX
eval `/usr/libexec/path_helper -s`

# Source Prezto.
test -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" && source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"

# Customize to your needs...

## Done by prezto ruby module
# export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

## Done by prezto nvm module
# NVM
# export NVM_DIR=~/.nvm
# source $(brew --prefix nvm)/nvm.sh

# HomeBrew
test -e "${HOME}/.homebrew.sh" && source "${HOME}/.homebrew.sh"

# init PYenv
# eval "$(pyenv init -)"

# added by travis gem
test -f "${HOME}/.travis/travis.sh" && source "${HOME}/.travis/travis.sh"

# iTerm2
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
